spring:
  application:
    name: paperless-ai-flow
  main:
    web-application-type: none
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        base-url: https://openrouter.ai/api

paperless:
  api:
    base-url: ${PAPERLESS_BASE_URL}
    token: ${PAPERLESS_TOKEN}
  pipelines:
    - name: rechnungen_de
      selector:
        required-tags: ["ocr-manual"]
      polling:
        interval: 30s
        enabled: true
      ocr:
        model: openai/gpt-4o
      patches:
        - action: add
          type: tag
          name: erhardt consulting
        - action: add
          type: tag
          name: ocr-manual
        - action: add
          type: tag
          name: Eingang

logging:
  level:
    consulting.erhardt.paperless_ai_flow: DEBUG
    org.springframework.integration: DEBUG
