spring:
  application:
    name: paperless-ai-flow
  main:
    web-application-type: none
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        base-url: https://openrouter.ai/api

paperless:
  api:
    base-url: ${PAPERLESS_BASE_URL}
    token: ${PAPERLESS_TOKEN}
  pipelines:
    - name: rechnungen_de
      selector:
        required-tags: ["ocr-manual"]
      polling:
        interval: 30s
        enabled: true
      ocr:
        model: openai/gpt-4o
        prompt: |
          Just transcribe the text in this image and preserve the formatting and layout (high quality OCR).
          Do that for ALL the text in the image. Be thorough and pay attention. This is very important.
          The image is from a text document so be sure to continue until the bottom of the page.
          Thanks a lot! You tend to forget about some text in the image so please focus! Use markdown format but without a code block.

logging:
  level:
    consulting.erhardt.paperless_ai_flow: DEBUG
    org.springframework.integration: DEBUG
