spring:
  application:
    name: paperless-ai-flow
  main:
    web-application-type: none
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        base-url: https://openrouter.ai/api

paperless:
  api:
    base-url: ${PAPERLESS_BASE_URL}
    token: ${PAPERLESS_TOKEN}
  pipelines: []

logging:
  level:
    consulting.erhardt.paperless_ai_flow: DEBUG
    org.springframework.integration: DEBUG
